# Uncomment the next line to define a global platform for your project

source 'https://github.com/cocoapods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

target 'LiveStreamingAndViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod'BDLive', '1.15.0', :subspecs => [
    'LiveStreaming',
    'Viewer',
  ]

end
