source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
         end
    end
  end
end

target 'PlayerHD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Player
  pod 'BDLive', '1.20.0'

end
