source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '11.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' # 不加Xcode14.3 报错
         end
    end
  end
end

target 'FloatingPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FloatingPlayer
  pod 'YYCategories'
  pod 'BDLive', '1.31.0'
  # pod 'BDLive', '1.31.0-static-ttsdk'
  # pod 'BDLive/ViewerWithoutRTC', '1.31.0-static-ttsdk'

end
