# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/cocoapods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

target 'LiveStreaming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod'BDLive', '1.21.0', :subspecs => [
    'LiveStreaming',
  ]
  # Pods for LiveStreaming

end
