# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/cocoapods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0' # 不加Xcode14.3 报错
         end
    end
  end
end

target 'LiveStreaming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'BDLive', '1.28.0', :subspecs => [
    'LiveStreaming',
    'ScreenShare',
  ]
  # Pods for LiveStreaming

end
