source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '9.0'

target 'Player' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Player
  pod 'BDLive', '1.17.0'

end
