source 'https://cdn.cocoapods.org'
source 'https://github.com/volcengine/volcengine-specs.git'

platform :ios, '11.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' # 不加Xcode14.3 报错
         end
    end
  end
end

def bdlive
  pod 'BDLive', '1.43.1'
end

def bdlive_no_rtc
  pod 'BDLive/ViewerWithoutRTC', '1.43.1'
end

def bdlive_ttsdk_static
  pod 'BDLive', '1.43.1-static-ttsdk'
end

def bdlive_ttsdk_static_no_rtc
  pod 'BDLive/ViewerWithoutRTC', '1.43.1-static-ttsdk'
end

target 'TwoBasePlayer' do 
  bdlive
end
